// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

class FlacMetadata {
  final StreamInfo streamInfo;
  final Map<String, String> tags;
  final String vendorString;
  final List<PictureBlockInfo> pictures;
  final BigInt audioDataStartOffset;
  final BigInt bytesInspected;

  const FlacMetadata({
    required this.streamInfo,
    required this.tags,
    required this.vendorString,
    required this.pictures,
    required this.audioDataStartOffset,
    required this.bytesInspected,
  });

  @override
  int get hashCode =>
      streamInfo.hashCode ^
      tags.hashCode ^
      vendorString.hashCode ^
      pictures.hashCode ^
      audioDataStartOffset.hashCode ^
      bytesInspected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlacMetadata &&
          runtimeType == other.runtimeType &&
          streamInfo == other.streamInfo &&
          tags == other.tags &&
          vendorString == other.vendorString &&
          pictures == other.pictures &&
          audioDataStartOffset == other.audioDataStartOffset &&
          bytesInspected == other.bytesInspected;
}

class PictureBlockInfo {
  final int pictureType;
  final String mimeType;
  final String description;
  final int width;
  final int height;
  final BigInt dataOffset;
  final int dataLength;

  const PictureBlockInfo({
    required this.pictureType,
    required this.mimeType,
    required this.description,
    required this.width,
    required this.height,
    required this.dataOffset,
    required this.dataLength,
  });

  @override
  int get hashCode =>
      pictureType.hashCode ^
      mimeType.hashCode ^
      description.hashCode ^
      width.hashCode ^
      height.hashCode ^
      dataOffset.hashCode ^
      dataLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PictureBlockInfo &&
          runtimeType == other.runtimeType &&
          pictureType == other.pictureType &&
          mimeType == other.mimeType &&
          description == other.description &&
          width == other.width &&
          height == other.height &&
          dataOffset == other.dataOffset &&
          dataLength == other.dataLength;
}

class RangeMeasurement {
  final String url;
  final String rangeHeader;
  final int statusCode;
  final Duration dnsAndConnectTime;
  final Duration timeToFirstByte;
  final Duration totalDownloadTime;
  final BigInt bytesDownloaded;
  final double speedMbps;

  const RangeMeasurement({
    required this.url,
    required this.rangeHeader,
    required this.statusCode,
    required this.dnsAndConnectTime,
    required this.timeToFirstByte,
    required this.totalDownloadTime,
    required this.bytesDownloaded,
    required this.speedMbps,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      rangeHeader.hashCode ^
      statusCode.hashCode ^
      dnsAndConnectTime.hashCode ^
      timeToFirstByte.hashCode ^
      totalDownloadTime.hashCode ^
      bytesDownloaded.hashCode ^
      speedMbps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RangeMeasurement &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          rangeHeader == other.rangeHeader &&
          statusCode == other.statusCode &&
          dnsAndConnectTime == other.dnsAndConnectTime &&
          timeToFirstByte == other.timeToFirstByte &&
          totalDownloadTime == other.totalDownloadTime &&
          bytesDownloaded == other.bytesDownloaded &&
          speedMbps == other.speedMbps;
}

class StreamInfo {
  final int minBlockSize;
  final int maxBlockSize;
  final int minFrameSize;
  final int maxFrameSize;
  final int sampleRate;
  final int channels;
  final int bitsPerSample;
  final BigInt totalSamples;
  final U8Array16 md5;
  final double durationSeconds;

  const StreamInfo({
    required this.minBlockSize,
    required this.maxBlockSize,
    required this.minFrameSize,
    required this.maxFrameSize,
    required this.sampleRate,
    required this.channels,
    required this.bitsPerSample,
    required this.totalSamples,
    required this.md5,
    required this.durationSeconds,
  });

  @override
  int get hashCode =>
      minBlockSize.hashCode ^
      maxBlockSize.hashCode ^
      minFrameSize.hashCode ^
      maxFrameSize.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitsPerSample.hashCode ^
      totalSamples.hashCode ^
      md5.hashCode ^
      durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamInfo &&
          runtimeType == other.runtimeType &&
          minBlockSize == other.minBlockSize &&
          maxBlockSize == other.maxBlockSize &&
          minFrameSize == other.minFrameSize &&
          maxFrameSize == other.maxFrameSize &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitsPerSample == other.bitsPerSample &&
          totalSamples == other.totalSamples &&
          md5 == other.md5 &&
          durationSeconds == other.durationSeconds;
}
