// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RangeFetcher>>
abstract class RangeFetcher implements RustOpaqueInterface {
  /// Fetches a specific byte range over HTTP and returns the data along with latency measurements.
  Future<(Uint8List, RangeMeasurement)> fetchRange(
      {required String url,
      required BigInt startByte,
      required BigInt endByte,
      Str? authToken});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RangeFetcher> newInstance() =>
      RustLib.instance.api.crateApiCloudRangeFetcherRangeFetcherNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<str>>
abstract class Str implements RustOpaqueInterface {}
