// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

AudioDevice getDummyAudioDevice() =>
    RustLib.instance.api.crateApiSimpleGetDummyAudioDevice();

AudioMetadata getFlacMetadata({required List<int> audioData}) =>
    RustLib.instance.api.crateApiSimpleGetFlacMetadata(audioData: audioData);

class AudioDevice {
  final String name;
  final bool bitPerfectCapable;
  final int maxSampleRate;

  const AudioDevice({
    required this.name,
    required this.bitPerfectCapable,
    required this.maxSampleRate,
  });

  @override
  int get hashCode =>
      name.hashCode ^ bitPerfectCapable.hashCode ^ maxSampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bitPerfectCapable == other.bitPerfectCapable &&
          maxSampleRate == other.maxSampleRate;
}

class AudioMetadata {
  final int sampleRate;
  final int channels;
  final int bitDepth;

  const AudioMetadata({
    required this.sampleRate,
    required this.channels,
    required this.bitDepth,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ channels.hashCode ^ bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetadata &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitDepth == other.bitDepth;
}
