// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

DecodedAudio decodeFlacFull({required List<int> audioData}) =>
    RustLib.instance.api.crateApiSimpleDecodeFlacFull(audioData: audioData);

String initAudioPlayback({required int sampleRate, required int channels}) =>
    RustLib.instance.api.crateApiSimpleInitAudioPlayback(
        sampleRate: sampleRate, channels: channels);

TrackMetadata scanLocalFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleScanLocalFile(path: path);

List<TrackMetadata> scanDirectory({required String path}) =>
    RustLib.instance.api.crateApiSimpleScanDirectory(path: path);

class DecodedAudio {
  final int sampleRate;
  final int channels;
  final int totalSamples;
  final Float32List firstFrameSamples;

  const DecodedAudio({
    required this.sampleRate,
    required this.channels,
    required this.totalSamples,
    required this.firstFrameSamples,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      channels.hashCode ^
      totalSamples.hashCode ^
      firstFrameSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedAudio &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          totalSamples == other.totalSamples &&
          firstFrameSamples == other.firstFrameSamples;
}

class TrackMetadata {
  final String path;
  final String title;
  final String artist;
  final String album;
  final int durationMs;
  final int sampleRate;
  final int channels;

  const TrackMetadata({
    required this.path,
    required this.title,
    required this.artist,
    required this.album,
    required this.durationMs,
    required this.sampleRate,
    required this.channels,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadata &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          sampleRate == other.sampleRate &&
          channels == other.channels;
}
