[package]
name = "rust_lib_bitdrop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
crossbeam-channel = "0.5.17"
flutter_rust_bridge = "=2.0.0"
lazy_static = "1.5.1"

symphonia = { version = "0.5.3", features = ["all"] }


tokio = { version = "1.38", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
byteorder = "1.5"
anyhow = "1.0"

rusqlite = { version = "0.31", features = ["bundled"] }

[target.'cfg(target_os = "android")'.dependencies]
oboe = "0.6.1"


[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
cpal = "0.15"

